image: registry.gitlab.com/vhiribarren/beacon-simulator-android:android-ci-24

before_script:
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew dependencies || true  # Trick otherwise getting constraint layout fails
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

unitTests:
  stage: test
  script:
    - ./gradlew dependencies || true  # Trick otherwise getting constraint layout fails
    - ./gradlew test

.functionalTests: # Disabled
  stage: test
  script:
    - $CI_TOOLS/android-sdk-linux/tools/emulator64-x86 -avd test -no-window -no-audio &
    - $CI_TOOLS/android-wait-for-emulator
    - adb shell input keyevent 82
    - ./gradlew dependencies || true  # Trick otherwise getting constraint layout fails
    - ./gradlew cAT